dist: xenial
language: python
python:
  - "3.4"
  - "3.6"
  - "3.7"
addons:
  apt:
    packages:
      - make
      - libz-dev
install:
  - pip install -r build_requirements.txt
env:
  - PYTHON_CONFIG=python-config
script:
  - make test
